variables:
  - &ci_image 'cont-reg.bjodah.se:443/bjodah/triceratops-6:33'

when:
  - event: [push]

steps:

  - name: restore-cache
    image: *ci_image
    commands:
      - curl -LO ftp://whisper_streaming:$${ARTIFACTS_PASS}@$${FTP_SERVER}/cache/cache-ci.tar || true
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: bjodah/whisper_streaming

  - name: run-test-suite
    image: *ci_image
    commands:
      - if [ -e ./cache-ci.tar ]; then tar -C / -xf `realpath ./cache-ci.tar`; fi
      - bash -lc 'curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.11.1'
      - bash -lc 'ln -s $(compgen -G /opt-3/cpython-v3.*-apt-deb/bin/pytest) /usr/local/bin/pytest'
      - bash -lc "./scripts/build-test-lint-all.sh"
      - find $(bash -lc 'go env GOMODCACHE') -type f -mtime +90 -exec rm {} \;
      - tar -C / -cf cache-ci.tar $(bash -lc 'go env GOMODCACHE')
      - curl -T cache-ci.tar ftp://whisper_streaming:$${ARTIFACTS_PASS}@$${FTP_SERVER}/cache/
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: bjodah/whisper_streaming
    depends_on:
      - restore-cache

