variables:
  - &ci_image 'cont-reg.bjodah.se:443/bjodah/triceratops-6:61'

when:
  - event: [push]

steps:

  - name: run-test-suite
    image: *ci_image
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      FTP_SERVER:
        from_secret: FTP_SERVER
      ARTIFACTS_PASS:
        from_secret: ARTIFACTS_PASS
    commands:
      - ( curl --connect-timeout 3 ftp://${CI_REPO_NAME}:$${ARTIFACTS_PASS}@$${FTP_SERVER}/cache/cache-ci.tar.zst | zstd -d | tar x -C / ) || true
      #- bash -lc 'curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.11.1'
      - bash -lc 'ln -s $(compgen -G /opt-3/cpython-v3.*-apt-deb/bin/pytest) /usr/local/bin/pytest'
      - bash -lc "./scripts/build-test-lint-all.sh"
      - find $(bash -lc 'go env GOMODCACHE') -type f -mtime +90 -exec rm {} \;
      - ( tar -C / -cf - $(bash -lc 'go env GOMODCACHE') | zstd -1 -T2 | curl -T - --connect-timeout 3 ftp://${CI_REPO_NAME}:$${ARTIFACTS_PASS}@$${FTP_SERVER}/cache/cache-ci.tar.zst ) || true
    when:
      - event: push
        repo: bjodah/whisper_streaming
